/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaJNI */

#ifndef _Included_JavaJNI
#define _Included_JavaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaJNI
 * Method:    JNI_callSumFunc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JavaJNI_JNI_1callSumFunc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaJNI
 * Method:    JNI_callDiff
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JavaJNI_JNI_1callDiff
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaJNI
 * Method:    JNI_callProdFunc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JavaJNI_JNI_1callProdFunc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaJNI
 * Method:    JNI_callDivFunc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JavaJNI_JNI_1callDivFunc
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
